#SPDX-License-Identifier: MIT-0
---
# tasks file for filebeat
# - name: Download and install the Debian package manually
#   ansible.builtin.get_url:
#     url: "{{ filebeat_deb_url }}"
#     dest: "/tmp/filebeat-{{ filebeat_version }}.deb"
#     mode: "0644"

- name: Install filebeat package
  ansible.builtin.apt:
    deb: "/tmp/filebeat-{{ filebeat_version }}-amd64.deb"
    state: present

- name: Configure filebeat
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart filebeat

- name: Enable and start filebeat
  ansible.builtin.service:
    name: filebeat
    enabled: yes
    state: started