#SPDX-License-Identifier: MIT-0
---
# tasks file for HAProxy
- name: Install HAProxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Copy HAProxy configuration
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0777'
    
  notify: Restart HAProxy