#SPDX-License-Identifier: MIT-0
---
# tasks file for patroni
- name: Check if PostgreSQL is installed
  ansible.builtin.shell: dpkg -l | grep postgresql-14
  register: postgres_installed
  ignore_errors: true
  changed_when: false

- name: Run prepare.yml if PostgreSQL is not installed
  ansible.builtin.include_tasks: prepare.yml
  when: postgres_installed.rc != 0

- name: Run setup.yml if PostgreSQL is installed
  ansible.builtin.include_tasks: setup.yml
  when: postgres_installed.rc == 0