---

- name: Install postgres
  ansible.builtin.apt:
    name: postgresql-14
    state: present
    update_cache: yes

- name: Stop postgres
  ansible.builtin.systemd:
    name: postgresql
    state: stopped
    enabled: no

- name: Remove postgres
  file:
    path: "{{ data_dir }}"
    state: absent