#SPDX-License-Identifier: MIT-0
---
# tasks file for grafana

- name: Install dependencies (Debian)
  apt:
    name: [apt-transport-https, software-properties-common, wget, gpg]
    state: present
    update_cache: yes

- name: Download Grafana .deb package
  get_url:
    url: "https://dl.grafana.com/oss/release/grafana_10.3.3_amd64.deb"
    dest: "/tmp/grafana_10.3.3_amd64.deb"

- name: Install Grafana from .deb package
  apt:
    deb: "/tmp/grafana_10.3.3_amd64.deb"

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started