---
# - name: Install Prometheus
#   hosts: monitoring
#   become: yes

#   roles: 
#     - prometheus

# - name: Install exporter
#   hosts: all
#   become: yes

#   roles:
#     - node_exporter

- name: Install postgres_exporter
  hosts: patroni
  become: yes
  
  roles:
    - postgres_exporter

# - name: Install grafana
#   hosts: monitoring
#   become: yes
  
#   roles:
#     - grafana