---
- name: Install elk
  hosts: logs
  become: yes

  roles:
    # - elasticsearch
    # - kibana
    - logstash

# - name: Install filebeat
#   hosts: patroni
#   become: yes
#   roles:
#     - filebeat