#SPDX-License-Identifier: MIT-0
---
# tasks file for kibana
# - name: Download and install the Debian package manually
#   ansible.builtin.get_url:
#     url: "{{ kibana_deb_url }}"
#     dest: "/tmp/kibana-{{ kibana_version }}.deb"
#     mode: "0644"

- name: Install kibana package
  ansible.builtin.apt:
    deb: "/tmp/kibana-{{ kibana_version }}-amd64.deb"
    state: present

- name: Configure Kibana
  ansible.builtin.template:
    src: kibana.j2
    dest: /etc/kibana/kibana.yml
    owner: kibana
    group: kibana
    mode: '0644'
  notify: Restart Kibana

- name: Enable and start Kibana service
  ansible.builtin.systemd:
    name: kibana
    enabled: yes
    state: started