#SPDX-License-Identifier: MIT-0
---
# tasks file for keepalived

- name: Add user
  ansible.builtin.user:
    name: keepalived_script
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Install Keep Alived
  ansible.builtin.apt:
    name: keepalived
    state: present

- name: Start and enable service
  ansible.builtin.systemd:
    name: keepalived
    state: started
    enabled: yes

- name: Copy config
  ansible.builtin.template:
    src: keepalive.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify:
    - Restart keepalive