#SPDX-License-Identifier: MIT-0
---
- name: Prepare Install
  ansible.builtin.include_tasks: tasks/prepare.yml

- name: Install java
  ansible.builtin.include_tasks: tasks/install_java.yml

- name: Install elasticsearch
  ansible.builtin.include_tasks: tasks/install_es.yml